In [25]:
import pandas as pd

df = pd.read_csv("../MetObjects.csv", dtype=str)

In [ ]:
# Prints first five objects 
df.head()

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,River,Classification,Rights and Reproduction,Link Resource,Object Wikidata URL,Metadata Date,Repository,Tags,Tags AAT URL,Tags Wikidata URL
0,1979.486.1,False,False,False,1,NaN,The American Wing,1979,Coin,One-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/1,NaN,8/14/2024 4:52:51 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
1,1980.264.5,False,False,False,2,NaN,The American Wing,1980,Coin,Ten-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/2,NaN,8/14/2024 4:52:51 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
2,67.265.9,False,False,False,3,NaN,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/3,NaN,4/6/2021 4:41:04 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
3,67.265.10,False,False,False,4,NaN,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/4,NaN,1/10/2024 4:57:19 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
4,67.265.11,False,False,False,5,NaN,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/5,NaN,1/10/2024 4:57:19 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN

In [ ]:
# Prints the column headers
df.columns

Index(['Object Number', 'Is Highlight', 'Is Timeline Work', 'Is Public Domain',
       'Object ID', 'Gallery Number', 'Department', 'AccessionYear',
       'Object Name', 'Title', 'Culture', 'Period', 'Dynasty', 'Reign',
       'Portfolio', 'Constituent ID', 'Artist Role', 'Artist Prefix',
       'Artist Display Name', 'Artist Display Bio', 'Artist Suffix',
       'Artist Alpha Sort', 'Artist Nationality', 'Artist Begin Date',
       'Artist End Date', 'Artist Gender', 'Artist ULAN URL',
       'Artist Wikidata URL', 'Object Date', 'Object Begin Date',
       'Object End Date', 'Medium', 'Dimensions', 'Credit Line',
       'Geography Type', 'City', 'State', 'County', 'Country', 'Region',
       'Subregion', 'Locale', 'Locus', 'Excavation', 'River', 'Classification',
       'Rights and Reproduction', 'Link Resource', 'Object Wikidata URL',
       'Metadata Date', 'Repository', 'Tags', 'Tags AAT URL',
       'Tags Wikidata URL'],
      dtype='str')

In [ ]:
# Filters to only show Object ID, Title and Object Name
df[["Object ID", "Title", "Object Name"]]

,Object ID,Title,Object Name
0,1,One-dollar Liberty Head Coin,Coin
1,2,Ten-dollar Liberty Head Coin,Coin
2,3,Two-and-a-Half Dollar Coin,Coin
3,4,Two-and-a-Half Dollar Coin,Coin
4,5,Two-and-a-Half Dollar Coin,Coin
...,...,...,...
503007,981446,"The adoration of the shepherds, with the Holy ...",Print
503008,981448,Landscape with a milkmaid at right and a boy a...,Print
503009,981457,Landscape with a milkmaid at right and a boy a...,Print
503010,981460,The deluge (copy in reverse),Print
503011,981463,Six saints,Print

In [ ]:
# Shows index location 0
df.iloc[0]

Object Number                                                     1979.486.1
Is Highlight                                                           False
Is Timeline Work                                                       False
Is Public Domain                                                       False
Object ID                                                                  1
Gallery Number                                                           NaN
Department                                                 The American Wing
AccessionYear                                                           1979
Object Name                                                             Coin
Title                                           One-dollar Liberty Head Coin
Culture                                                                  NaN
Period                                                                   NaN
Dynasty                                                                  NaN
Reign                                                                    NaN
Portfolio                                                                NaN
Constituent ID                                                         16429
Artist Role                                                            Maker
Artist Prefix
Artist Display Name                                    James Barton Longacre
Artist Display Bio         American, Delaware County, Pennsylvania 1794–1...
Artist Suffix
Artist Alpha Sort                                     Longacre, James Barton
Artist Nationality                                                  American
Artist Begin Date                                                 1794
Artist End Date                                                   1869
Artist Gender                                                            NaN
Artist ULAN URL                   http://vocab.getty.edu/page/ulan/500011409
Artist Wikidata URL                   https://www.wikidata.org/wiki/Q3806459
Object Date                                                             1853
Object Begin Date                                                       1853
Object End Date                                                         1853
Medium                                                                  Gold
Dimensions                                            Dimensions unavailable
Credit Line                               Gift of Heinz L. Stoppelmann, 1979
Geography Type                                                           NaN
City                                                                     NaN
State                                                                    NaN
County                                                                   NaN
Country                                                                  NaN
Region                                                                   NaN
Subregion                                                                NaN
Locale                                                                   NaN
Locus                                                                    NaN
Excavation                                                               NaN
River                                                                    NaN
Classification                                                           NaN
Rights and Reproduction                                                  NaN
Link Resource               http://www.metmuseum.org/art/collection/search/1
Object Wikidata URL                                                      NaN
Metadata Date                                           8/14/2024 4:52:51 AM
Repository                          Metropolitan Museum of Art, New York, NY
Tags                                                                     NaN
Tags AAT URL                                                             NaN
Tags Wikidata URL                                                        NaN
Name: 0, dtype: str

In [ ]:
# Shows only objects with an Object Name that is Print
df[df["Object Name"] == 'Print']

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,River,Classification,Rights and Reproduction,Link Resource,Object Wikidata URL,Metadata Date,Repository,Tags,Tags AAT URL,Tags Wikidata URL
6301,83.2.333,False,False,True,6781,NaN,The American Wing,1883,Print,Print,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search...,NaN,1/30/2025 4:54:21 AM,"Metropolitan Museum of Art, New York, NY",Men|Profiles,http://vocab.getty.edu/page/aat/300025928|http...,https://www.wikidata.org/wiki/Q8441|https://ww...
13076,1991.219.1,False,False,True,14292,729,The American Wing,1991,Print,Framed Print,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search...,https://www.wikidata.org/wiki/Q116241042,2/7/2023 4:46:51 AM,"Metropolitan Museum of Art, New York, NY",Women|Camels,http://vocab.getty.edu/page/aat/300025943|http...,https://www.wikidata.org/wiki/Q467|https://www...
13077,1991.219.2,False,False,True,14293,729,The American Wing,1991,Print,Framed Print,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search...,https://www.wikidata.org/wiki/Q116241051,2/7/2023 4:46:51 AM,"Metropolitan Museum of Art, New York, NY",Shields|Women|Emblems,http://vocab.getty.edu/page/aat/300036869|http...,https://www.wikidata.org/wiki/Q131559|https://...
13078,1991.219.3,False,False,True,14294,NaN,The American Wing,1991,Print,Framed Print,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search...,NaN,4/6/2021 4:41:04 AM,"Metropolitan Museum of Art, New York, NY",Men|Lions|Snakes|Plants,http://vocab.getty.edu/page/aat/300025928|http...,https://www.wikidata.org/wiki/Q8441|https://ww...
13079,1991.219.4,False,False,True,14295,NaN,The American Wing,1991,Print,An Emblem of America,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search...,NaN,1/30/2025 4:54:21 AM,"Metropolitan Museum of Art, New York, NY",Bow and Arrow|Women,|http://vocab.getty.edu/page/aat/300025943,https://www.wikidata.org/wiki/Q19827042|https:...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503007,22.73.3-162,False,False,False,981446,NaN,Drawings and Prints,1922,Print,"The adoration of the shepherds, with the Holy ...",...,NaN,Prints,NaN,http://www.metmuseum.org/art/collection/search...,NaN,10/24/2026 4:53:43 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
503008,57.578.3,False,False,False,981448,NaN,Drawings and Prints,1957,Print,Landscape with a milkmaid at right and a boy a...,...,NaN,Prints,NaN,http://www.metmuseum.org/art/collection/search...,NaN,10/24/2026 4:53:43 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
503009,22.73.3-118,False,False,False,981457,NaN,Drawings and Prints,1922,Print,Landscape with a milkmaid at right and a boy a...,...,NaN,Prints,NaN,http://www.metmuseum.org/art/collection/search...,NaN,10/24/2026 4:53:43 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
503010,18.17.3-151,False,False,False,981460,NaN,Drawings and Prints,1918,Print,The deluge (copy in reverse),...,NaN,Prints,NaN,http://www.metmuseum.org/art/collection/search...,NaN,10/24/2026 4:53:43 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
503011,22.73.3-116,False,False,False,981463,NaN,Drawings and Prints,1922,Print,Six saints,...,NaN,Prints,NaN,http://www.metmuseum.org/art/collection/search...,NaN,10/24/2026 4:53:43 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN

In [ ]:
# Looks for objects from ONLY Denmark
df[df["Country"].isin(["Denmark"])]

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,River,Classification,Rights and Reproduction,Link Resource,Object Wikidata URL,Metadata Date,Repository,Tags,Tags AAT URL,Tags Wikidata URL
337541,Inst.1983.4.1,False,False,True,504222,NaN,Musical Instruments,NaN,Portrait of the Father of Emilius Nicolai Scherr,Portrait of the Father of Emilius Nicolai Scherr,...,NaN,Paintings,NaN,http://www.metmuseum.org/art/collection/search...,https://www.wikidata.org/wiki/Q78625660,9/16/2020 6:35:19 PM,"Metropolitan Museum of Art, New York, NY",Men|Portraits,http://vocab.getty.edu/page/aat/300025928|http...,https://www.wikidata.org/wiki/Q8441|https://ww...
338009,89.4.3339,False,False,False,504751,NaN,Musical Instruments,1889,Pottery Whistle,Pottery Whistle,...,NaN,Aerophone-Whistle Flute-vessel flute,NaN,http://www.metmuseum.org/art/collection/search...,NaN,5/19/2023 4:53:50 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
489109,663.1 C79,False,False,True,912212,NaN,The Libraries,NaN,NaN,Nordiske oldsager i det Kongelige museum i Kjö...,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search...,NaN,6/5/2026 4:55:53 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN

In [ ]:
# Filters out object from United States
df[~df["Country"].isin(["United States"])]

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,River,Classification,Rights and Reproduction,Link Resource,Object Wikidata URL,Metadata Date,Repository,Tags,Tags AAT URL,Tags Wikidata URL
0,1979.486.1,False,False,False,1,NaN,The American Wing,1979,Coin,One-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/1,NaN,8/14/2024 4:52:51 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
1,1980.264.5,False,False,False,2,NaN,The American Wing,1980,Coin,Ten-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/2,NaN,8/14/2024 4:52:51 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
2,67.265.9,False,False,False,3,NaN,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/3,NaN,4/6/2021 4:41:04 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
3,67.265.10,False,False,False,4,NaN,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/4,NaN,1/10/2024 4:57:19 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
4,67.265.11,False,False,False,5,NaN,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/5,NaN,1/10/2024 4:57:19 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503007,22.73.3-162,False,False,False,981446,NaN,Drawings and Prints,1922,Print,"The adoration of the shepherds, with the Holy ...",...,NaN,Prints,NaN,http://www.metmuseum.org/art/collection/search...,NaN,10/24/2026 4:53:43 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
503008,57.578.3,False,False,False,981448,NaN,Drawings and Prints,1957,Print,Landscape with a milkmaid at right and a boy a...,...,NaN,Prints,NaN,http://www.metmuseum.org/art/collection/search...,NaN,10/24/2026 4:53:43 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
503009,22.73.3-118,False,False,False,981457,NaN,Drawings and Prints,1922,Print,Landscape with a milkmaid at right and a boy a...,...,NaN,Prints,NaN,http://www.metmuseum.org/art/collection/search...,NaN,10/24/2026 4:53:43 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
503010,18.17.3-151,False,False,False,981460,NaN,Drawings and Prints,1918,Print,The deluge (copy in reverse),...,NaN,Prints,NaN,http://www.metmuseum.org/art/collection/search...,NaN,10/24/2026 4:53:43 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
503011,22.73.3-116,False,False,False,981463,NaN,Drawings and Prints,1922,Print,Six saints,...,NaN,Prints,NaN,http://www.metmuseum.org/art/collection/search...,NaN,10/24/2026 4:53:43 AM,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN

In [ ]:
# Drops all rows containing missing values
df.dropna()

Empty DataFrame
Columns: [Object Number, Is Highlight, Is Timeline Work, Is Public Domain, Object ID, Gallery Number, Department, AccessionYear, Object Name, Title, Culture, Period, Dynasty, Reign, Portfolio, Constituent ID, Artist Role, Artist Prefix, Artist Display Name, Artist Display Bio, Artist Suffix, Artist Alpha Sort, Artist Nationality, Artist Begin Date, Artist End Date, Artist Gender, Artist ULAN URL, Artist Wikidata URL, Object Date, Object Begin Date, Object End Date, Medium, Dimensions, Credit Line, Geography Type, City, State, County, Country, Region, Subregion, Locale, Locus, Excavation, River, Classification, Rights and Reproduction, Link Resource, Object Wikidata URL, Metadata Date, Repository, Tags, Tags AAT URL, Tags Wikidata URL]
Index: []

[0 rows x 54 columns]

In [ ]:
# fills all missing data fields with 0
# you can also do df.fillna({"Object Name": '0'}) for it to only be done to Object Name column
# you can add inplace=True to modify existing dataframe instead of returning a new one
df.fillna('0')

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,River,Classification,Rights and Reproduction,Link Resource,Object Wikidata URL,Metadata Date,Repository,Tags,Tags AAT URL,Tags Wikidata URL
0,1979.486.1,False,False,False,1,0,The American Wing,1979,Coin,One-dollar Liberty Head Coin,...,0,0,0,http://www.metmuseum.org/art/collection/search/1,0,8/14/2024 4:52:51 AM,"Metropolitan Museum of Art, New York, NY",0,0,0
1,1980.264.5,False,False,False,2,0,The American Wing,1980,Coin,Ten-dollar Liberty Head Coin,...,0,0,0,http://www.metmuseum.org/art/collection/search/2,0,8/14/2024 4:52:51 AM,"Metropolitan Museum of Art, New York, NY",0,0,0
2,67.265.9,False,False,False,3,0,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,0,0,0,http://www.metmuseum.org/art/collection/search/3,0,4/6/2021 4:41:04 AM,"Metropolitan Museum of Art, New York, NY",0,0,0
3,67.265.10,False,False,False,4,0,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,0,0,0,http://www.metmuseum.org/art/collection/search/4,0,1/10/2024 4:57:19 AM,"Metropolitan Museum of Art, New York, NY",0,0,0
4,67.265.11,False,False,False,5,0,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,0,0,0,http://www.metmuseum.org/art/collection/search/5,0,1/10/2024 4:57:19 AM,"Metropolitan Museum of Art, New York, NY",0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503007,22.73.3-162,False,False,False,981446,0,Drawings and Prints,1922,Print,"The adoration of the shepherds, with the Holy ...",...,0,Prints,0,http://www.metmuseum.org/art/collection/search...,0,10/24/2026 4:53:43 AM,"Metropolitan Museum of Art, New York, NY",0,0,0
503008,57.578.3,False,False,False,981448,0,Drawings and Prints,1957,Print,Landscape with a milkmaid at right and a boy a...,...,0,Prints,0,http://www.metmuseum.org/art/collection/search...,0,10/24/2026 4:53:43 AM,"Metropolitan Museum of Art, New York, NY",0,0,0
503009,22.73.3-118,False,False,False,981457,0,Drawings and Prints,1922,Print,Landscape with a milkmaid at right and a boy a...,...,0,Prints,0,http://www.metmuseum.org/art/collection/search...,0,10/24/2026 4:53:43 AM,"Metropolitan Museum of Art, New York, NY",0,0,0
503010,18.17.3-151,False,False,False,981460,0,Drawings and Prints,1918,Print,The deluge (copy in reverse),...,0,Prints,0,http://www.metmuseum.org/art/collection/search...,0,10/24/2026 4:53:43 AM,"Metropolitan Museum of Art, New York, NY",0,0,0
503011,22.73.3-116,False,False,False,981463,0,Drawings and Prints,1922,Print,Six saints,...,0,Prints,0,http://www.metmuseum.org/art/collection/search...,0,10/24/2026 4:53:43 AM,"Metropolitan Museum of Art, New York, NY",0,0,0

In [ ]:
# returns amount of occurrences for something
# amount of times a country is mentioned
df["Country"].value_counts()

Country
Egypt                   31508
United States            9166
Iran                     6345
Peru                     3394
France                   1770
                        ...
Great Britain               1
northern Uganda             1
Northern Nigeria            1
Southeast Turkey            1
Iran or North Africa        1
Name: count, Length: 983, dtype: int64